name: Assume AWS Role via OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq and AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y jq awscli

      - name: Get OIDC Token and Assume Role
        env:
          AWS_ROLE_ARN: arn:aws:iam::481008523238:role/sts-lab-2-target
          AWS_REGION: us-east-1
        run: |
          echo "Getting OIDC token..."
          ID_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)

          echo "Assuming role..."
          CREDS=$(aws sts assume-role-with-web-identity \
            --role-arn "$AWS_ROLE_ARN" \
            --role-session-name github-actions-session \
            --web-identity-token "$ID_TOKEN" \
            --duration-seconds 900)

          echo "✅ Role assumed!"
          echo "$CREDS" | jq .
